version: "3.8"
services:
  typescript-apollo-express-graphql-api:
    container_name: typescript-apollo-express-graphql-api
    hostname: typescript-apollo-express-graphql-api
    build:
      context: .
      dockerfile: ./typescript-apollo-express-graphql-api/Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./typescript-apollo-express-graphql-api:/server/app:rw
      - typescript-apollo-express-graphql-api-vol:/server/app/node_modules

  mongo-db:
    image: mongo
    container_name: mongo-db
    hostname: mongo-db
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret00
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongodata:/data/db
      - ./mongo/mongo-entrypoint:/docker-entrypoint-initdb.d:ro
    command: mongod

volumes:
  typescript-apollo-express-graphql-api-vol:
